### ISSUE TITLE
Logger output writes excess "." 

### ISSUE THREAD

**Issue by kbarnhart** [NorthernWidget/Logger#5]
The output data files for data loggers deployed on Niwot Ridge include excess periods (".") which results in the inability of Matlab to read in the data. The error seems to be common at the end of the text line, which is when the Decagon soil sensors are printed. 

The following two files have been added to the folder "excessPeriodsInOutput" in the "examples" folder. 
1. "logmega_Niwot_North.ino", the sketch for the North Site logger.
2. "NR_NORTH.TXT", the output text file.
.

**Comment by awickert** [comment]
This issue hasn't reappeared in over a year, and I think I recall clearing out some extra print statements, so this may be part of it. Although I thought these were Serial.print() statements...

In any case, not an issue with any up-to-date boards; closing.
